import { useState, useEffect } from 'react';
import { ChevronLeft, Sparkles, Download, Trash2, Fingerprint, Link, CircleAlert, Pencil, X, Plus, FolderOpen } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { confirm as confirmDialog } from '@tauri-apps/plugin-dialog';
import { useAccountStore } from '../stores/useAccountStore';
import * as accountService from '../services/accountService';
import { FingerprintWithStats, Account, DeviceProfile } from '../types/account';
import { getSubscriptionTier } from '../utils/account';
import { Page } from '../types/navigation';
import { OverviewTabsHeader } from '../components/OverviewTabsHeader';
import { useEscClose } from '../hooks/useEscClose';
import { FileCorruptedModal, parseFileCorruptedError } from '../components/FileCorruptedModal';
import { ModalErrorMessage, useModalErrorState } from '../components/ModalErrorMessage';

interface FingerprintsPageProps {
  onNavigate?: (page: Page) => void;
}

export function FingerprintsPage({ onNavigate }: FingerprintsPageProps) {
  const { t } = useTranslation();
  const { accounts, fetchAccounts } = useAccountStore();
  const [fingerprints, setFingerprints] = useState<FingerprintWithStats[]>([]);
  const [loading, setLoading] = useState(true);
  const [actionLoading, setActionLoading] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const [showNameModal, setShowNameModal] = useState<'generate' | 'capture' | null>(null);
  const [newName, setNewName] = useState('');
  const [previewProfile, setPreviewProfile] = useState<DeviceProfile | null>(null);
  const [previewAutoGeneratedFields, setPreviewAutoGeneratedFields] = useState<Set<string>>(new Set());
  const [previewLoading, setPreviewLoading] = useState(false);
  const {
    message: previewError,
    scrollKey: previewErrorScrollKey,
    set: setPreviewError,
  } = useModalErrorState();
  const [duplicateFingerprint, setDuplicateFingerprint] = useState<FingerprintWithStats | null>(null);
  const [showImportModal, setShowImportModal] = useState(false);
  const [importJson, setImportJson] = useState('');
  const [importing, setImporting] = useState(false);
  const {
    message: importError,
    scrollKey: importErrorScrollKey,
    set: setImportError,
  } = useModalErrorState();
  const [showBoundAccounts, setShowBoundAccounts] = useState<string | null>(null);
  const [boundAccounts, setBoundAccounts] = useState<Account[]>([]);
  const [showAddAccounts, setShowAddAccounts] = useState(false);
  const {
    message: boundAccountsError,
    scrollKey: boundAccountsErrorScrollKey,
    set: setBoundAccountsError,
  } = useModalErrorState();
  const [selectedAccountIds, setSelectedAccountIds] = useState<Set<string>>(new Set());
  const [selectedFpIds, setSelectedFpIds] = useState<Set<string>>(new Set());
  const [showRenameModal, setShowRenameModal] = useState<string | null>(null);
  const [renameName, setRenameName] = useState('');
  const {
    message: renameError,
    scrollKey: renameErrorScrollKey,
    set: setRenameError,
  } = useModalErrorState();
  const [showDetailModal, setShowDetailModal] = useState<FingerprintWithStats | null>(null);
  const [fileCorruptedError, setFileCorruptedError] = useState<{
    error_type: 'file_corrupted';
    file_name: string;
    file_path: string;
    original_error: string;
  } | null>(null);

  useEffect(() => {
    loadFingerprints();
    fetchAccounts();
  }, []);

  const loadFingerprints = async () => {
    setLoading(true);
    try {
      const list = await accountService.listFingerprints();
      setFingerprints(list);
      setSelectedFpIds((prev) => {
        const allowed = new Set(list.filter(fp => !fp.is_original).map(fp => fp.id));
        return new Set(Array.from(prev).filter(id => allowed.has(id)));
      });
    } catch (e) {
      const corrupted = parseFileCorruptedError(e);
      if (corrupted) {
        setFileCorruptedError(corrupted);
      } else {
        setMessage(t('common.failed'));
      }
    }
    setLoading(false);
  };

  const buildDefaultName = (mode: 'generate' | 'capture') => {
    const now = new Date();
    const pad = (value: number) => String(value).padStart(2, '0');
    const stamp = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${pad(now.getHours())}:${pad(now.getMinutes())}`;
    const prefix = mode === 'generate' ? t('fingerprints.modals.generate.btn') : t('fingerprints.modals.capture.btn');
    return `${prefix} ${stamp}`;
  };

  const normalizeProfileValue = (value?: string) => (value || '').trim();

  const isSameProfile = (a: DeviceProfile, b: DeviceProfile) =>
    a.machine_id === b.machine_id &&
    a.mac_machine_id === b.mac_machine_id &&
    a.dev_device_id === b.dev_device_id &&
    a.sqm_id === b.sqm_id &&
    normalizeProfileValue(a.service_machine_id) === normalizeProfileValue(b.service_machine_id);

  const resetPreviewState = () => {
    setPreviewProfile(null);
    setPreviewAutoGeneratedFields(new Set());
    setPreviewError(null);
    setDuplicateFingerprint(null);
  };

  const isAutoGeneratedField = (field: string) =>
    showNameModal === 'capture' && previewAutoGeneratedFields.has(field);

  const closePreviewModal = () => {
    if (actionLoading === 'generate' || actionLoading === 'capture') return;
    setShowNameModal(null);
    setNewName('');
    setPreviewLoading(false);
    resetPreviewState();
  };

  useEscClose(!!previewProfile, closePreviewModal);
  useEscClose(!!showRenameModal, () => { setShowRenameModal(null); setRenameName(''); setRenameError(null); });
  useEscClose(showImportModal, () => { if (!importing) { setShowImportModal(false); setImportError(null); } });
  useEscClose(!!showBoundAccounts, () => { setShowBoundAccounts(null); setBoundAccountsError(null); });
  useEscClose(!!showDetailModal, () => setShowDetailModal(null));

  useEffect(() => {
    if (!previewProfile) {
      setDuplicateFingerprint(null);
      return;
    }
    const duplicated = fingerprints.find((fp) => isSameProfile(fp.profile, previewProfile)) || null;
    setDuplicateFingerprint(duplicated);
  }, [previewProfile, fingerprints]);

  const openPreviewModal = async (mode: 'generate' | 'capture') => {
    setShowNameModal(mode);
    setNewName(buildDefaultName(mode));
    resetPreviewState();
    setPreviewLoading(true);
    try {
      if (mode === 'generate') {
        const profile = await accountService.previewGenerateProfile();
        setPreviewProfile(profile);
        setPreviewAutoGeneratedFields(new Set());
      } else {
        const result = await accountService.previewCurrentProfile();
        setPreviewProfile(result.profile);
        setPreviewAutoGeneratedFields(new Set(result.autoGeneratedFields || []));
      }
    } catch (e) {
      const corrupted = parseFileCorruptedError(e);
      if (corrupted) {
        setShowNameModal(null);
        setFileCorruptedError(corrupted);
      } else {
        setPreviewError(typeof e === 'string' ? e : t('common.failed'));
      }
    }
    setPreviewLoading(false);
  };

  const handleCreateFingerprint = async () => {
    if (!showNameModal) return;
    const trimmedName = newName.trim();
    if (!trimmedName) {
      setPreviewError(t('fingerprints.messages.enterName'));
      return;
    }
    if (!previewProfile) {
      setPreviewError(t('fingerprints.messages.previewNotReady'));
      return;
    }
    if (duplicateFingerprint) {
      return;
    }
    setActionLoading(showNameModal);
    let created = false;
    try {
      await accountService.createFingerprintWithProfile(trimmedName, previewProfile);
      setMessage(showNameModal === 'generate' ? t('fingerprints.messages.generated') : t('fingerprints.messages.captured'));
      await loadFingerprints();
      created = true;
    } catch (e) {
      const corrupted = parseFileCorruptedError(e);
      if (corrupted) {
        setShowNameModal(null);
        setFileCorruptedError(corrupted);
      } else {
        setPreviewError(typeof e === 'string' ? e : t('common.failed'));
      }
    }
    setActionLoading(null);
    if (created) {
      closePreviewModal();
    }
  };


  const handleImportFingerprintsFromTools = async () => {
    setImportError(null);
    setImporting(true);
    try {
      const imported = await accountService.importFingerprintsFromOldTools();
      setShowImportModal(false);
      setImportError(null);
      setMessage(t('fingerprints.messages.imported', { count: imported }));
      await loadFingerprints();
    } catch (e) {
      setImportError(typeof e === 'string' ? e : t('common.failed'));
    }
    setImporting(false);
  };

  const handleImportFingerprintsFromJson = async () => {
    if (!importJson.trim()) {
      setImportError(t('messages.jsonRequired'));
      return;
    }
    setImportError(null);
    setImporting(true);
    try {
      const imported = await accountService.importFingerprintsFromJson(importJson.trim());
      setShowImportModal(false);
      setImportJson('');
      setImportError(null);
      setMessage(t('fingerprints.messages.imported', { count: imported }));
      await loadFingerprints();
    } catch (e) {
      setImportError(typeof e === 'string' ? e : t('common.failed'));
    }
    setImporting(false);
  };

  const selectableFps = fingerprints.filter(fp => !fp.is_original);
  const allSelected = selectableFps.length > 0 && selectedFpIds.size === selectableFps.length;
  const unboundDeletableFps = selectableFps.filter(fp => fp.bound_account_count === 0);
  const unboundDeletableIdSet = new Set(unboundDeletableFps.map(fp => fp.id));
  const unboundDeletableCount = unboundDeletableFps.length;

  const toggleSelectFp = (fpId: string) => {
    setSelectedFpIds((prev) => {
      const next = new Set(prev);
      if (next.has(fpId)) next.delete(fpId);
      else next.add(fpId);
      return next;
    });
  };

  const toggleSelectAllFps = () => {
    if (allSelected) {
      setSelectedFpIds(new Set());
      return;
    }
    setSelectedFpIds(new Set(selectableFps.map(fp => fp.id)));
  };

  const handleBatchDelete = async () => {
    const targetIds = selectableFps.filter(fp => selectedFpIds.has(fp.id)).map(fp => fp.id);
    if (targetIds.length === 0) return;
    const confirmed = await confirmDialog(
      t('fingerprints.messages.batchDeleteConfirm', { count: targetIds.length })
    );
    if (!confirmed) return;
    setActionLoading('delete-selected');
    try {
      await Promise.all(targetIds.map(id => accountService.deleteFingerprint(id)));
      setMessage(t('fingerprints.messages.deleted'));
      setSelectedFpIds(new Set());
      await loadFingerprints();
    } catch (e) {
      setMessage(typeof e === 'string' ? e : t('common.failed'));
    }
    setActionLoading(null);
  };

  const handleDeleteUnboundFingerprints = async () => {
    if (unboundDeletableCount === 0) {
      setMessage(t('fingerprints.messages.noUnboundToDelete'));
      return;
    }

    const confirmed = await confirmDialog(
      t('fingerprints.messages.deleteUnboundConfirm', { count: unboundDeletableCount })
    );
    if (!confirmed) return;

    setActionLoading('delete-unbound');
    try {
      const deletedCount = await accountService.deleteUnboundFingerprints();
      if (deletedCount === 0) {
        setMessage(t('fingerprints.messages.noUnboundToDelete'));
      } else {
        setMessage(t('fingerprints.messages.deletedUnbound', { count: deletedCount }));
      }
      setSelectedFpIds((prev) => new Set(Array.from(prev).filter(id => !unboundDeletableIdSet.has(id))));
      await loadFingerprints();
    } catch (e) {
      setMessage(typeof e === 'string' ? e : t('common.failed'));
    }
    setActionLoading(null);
  };

  const openRenameModal = (fp: FingerprintWithStats) => {
    if (fp.is_original) return;
    setRenameName(fp.name);
    setRenameError(null);
    setShowRenameModal(fp.id);
  };

  const handleRenameFingerprint = async () => {
    if (!showRenameModal) return;
    const nextName = renameName.trim();
    if (!nextName) {
      setRenameError(t('fingerprints.messages.enterName'));
      return;
    }
    setRenameError(null);
    setActionLoading(`rename-${showRenameModal}`);
    try {
      await accountService.renameFingerprint(showRenameModal, nextName);
      setMessage(t('fingerprints.messages.renamed'));
      setShowRenameModal(null);
      setRenameName('');
      setRenameError(null);
      await loadFingerprints();
    } catch (e) {
      setRenameError(typeof e === 'string' ? e : t('common.failed'));
    }
    setActionLoading(null);
  };

  const isRenaming = showRenameModal ? actionLoading === `rename-${showRenameModal}` : false;

  const handleDelete = async (fpId: string) => {
    const confirmed = await confirmDialog(t('fingerprints.messages.deleteConfirm'));
    if (!confirmed) return;
    setActionLoading(fpId);
    try {
      await accountService.deleteFingerprint(fpId);
      setMessage(t('fingerprints.messages.deleted'));
      await loadFingerprints();
    } catch (e) {
      setMessage(typeof e === 'string' ? e : t('common.failed'));
    }
    setActionLoading(null);
  };

  const handleShowBoundAccounts = async (fpId: string) => {
    setShowBoundAccounts(fpId);
    setShowAddAccounts(false);
    setBoundAccountsError(null);
    setSelectedAccountIds(new Set());
    try {
      const accs = await accountService.getBoundAccounts(fpId);
      setBoundAccounts(accs);
    } catch (e) {
      setBoundAccounts([]);
    }
  };

  // 获取指纹名称
  const getFpName = (fpId?: string) => {
    if (!fpId || fpId === 'original') return t('modals.fingerprint.original');
    const fp = fingerprints.find(f => f.id === fpId);
    return fp?.name || fpId;
  };

  // 获取不属于当前指纹的账号
  const getOtherAccounts = () => {
    return accounts.filter(a => a.fingerprint_id !== showBoundAccounts);
  };

  // 添加账号到当前指纹
  const handleAddAccountsToFp = async () => {
    if (!showBoundAccounts || selectedAccountIds.size === 0) return;
    setBoundAccountsError(null);
    setActionLoading('add-accounts');
    try {
      for (const accId of selectedAccountIds) {
        await accountService.bindAccountFingerprint(accId, showBoundAccounts);
      }
      setMessage(t('fingerprints.messages.addedAccounts', { count: selectedAccountIds.size }));
      setShowAddAccounts(false);
      setBoundAccountsError(null);
      setSelectedAccountIds(new Set());
      await handleShowBoundAccounts(showBoundAccounts);
      await loadFingerprints();
      await fetchAccounts();
    } catch (e) {
      setBoundAccountsError(typeof e === 'string' ? e : t('common.failed'));
    }
    setActionLoading(null);
  };

  const openDetailModal = (fp: FingerprintWithStats) => {
    setShowDetailModal(fp);
  };

  return (
    <>
      <main className="main-content">
        <OverviewTabsHeader
          active="fingerprints"
          onNavigate={onNavigate}
          subtitle={t('fingerprints.subtitle')}
        />
        {/* Toolbar */}
        <div className="toolbar">
          <div className="toolbar-right">
            <button className="btn btn-primary" onClick={() => openPreviewModal('generate')} disabled={!!actionLoading || importing}>
              <Sparkles size={18} />{t('fingerprints.toolbar.generate')}
            </button>
            <button className="btn btn-secondary" onClick={() => openPreviewModal('capture')} disabled={!!actionLoading || importing}>
              <Download size={18} />{t('fingerprints.toolbar.capture')}
            </button>
            <button className="btn btn-secondary" onClick={() => setShowImportModal(true)} disabled={!!actionLoading || importing}>
              <Download size={18} />{t('fingerprints.toolbar.import')}
            </button>
            <button
              className="btn btn-secondary"
              onClick={handleDeleteUnboundFingerprints}
              disabled={!!actionLoading || importing || unboundDeletableCount === 0}
            >
              <Trash2 size={18} />{t('fingerprints.toolbar.deleteUnbound')} ({unboundDeletableCount})
            </button>
            {selectedFpIds.size > 0 && (
              <button className="btn btn-danger" onClick={handleBatchDelete} disabled={!!actionLoading || importing}>
                <Trash2 size={18} />{t('common.delete')} ({selectedFpIds.size})
              </button>
            )}
          </div>
        </div>

        {message && <div className="action-message" style={{ marginBottom: 16 }}>{message}</div>}

        {loading ? (
          <div className="empty-state"><div className="loading-spinner" style={{ width: 40, height: 40 }} /></div>
        ) : fingerprints.length === 0 ? (
          <div className="empty-state">
            <div className="icon"><Fingerprint size={40} /></div>
            <h3>{t('fingerprints.title')}</h3>
            <p>{t('fingerprints.subtitle')}</p>
            <button className="btn btn-primary" onClick={() => openPreviewModal('generate')}><Sparkles size={18} />{t('fingerprints.toolbar.generate')}</button>
          </div>
        ) : (
          <div className="account-table-container">
            <table className="account-table fingerprint-table">
              <thead>
                <tr>
                  <th style={{ width: 40 }}>
                    <input 
                      type="checkbox" 
                      checked={allSelected} 
                      onChange={toggleSelectAllFps}
                      disabled={selectableFps.length === 0}
                    />
                  </th>
                  <th style={{ width: 220 }}>{t('fingerprints.table.name')}</th>
                  <th>{t('fingerprints.table.machineId')}</th>
                  <th style={{ width: 140 }}>{t('fingerprints.table.accounts')}</th>
                  <th className="table-action-header" style={{ width: 140 }}>{t('fingerprints.table.actions')}</th>
                </tr>
              </thead>
              <tbody>
                {fingerprints.map((fp) => (
                  <tr key={fp.id} className={fp.is_current ? 'current' : ''}>
                    <td className="table-action-cell">
                      <input 
                        type="checkbox" 
                        checked={selectedFpIds.has(fp.id)} 
                        onChange={() => toggleSelectFp(fp.id)}
                        disabled={fp.is_original}
                      />
                    </td>
                    <td>
                      <div className="account-cell">
                        <div className="account-main-line">
                          <span className="account-email-text" title={fp.name}>
                            {fp.is_original && '📌 '}{fp.name}
                          </span>
                          {fp.is_current && <span className="mini-tag current">{t('fingerprints.messages.current')}</span>}
                        </div>
                        <div className="account-sub-line">
                          {fp.is_original && <span className="status-text" style={{ color: 'var(--text-muted)' }}>{t('fingerprints.messages.readOnly')}</span>}
                        </div>
                      </div>
                    </td>
                    <td>
                      <span style={{ fontFamily: 'monospace', fontSize: 13, color: 'var(--text-secondary)' }}>
                        {fp.profile.machine_id.slice(0, 25)}...
                      </span>
                    </td>
                    <td>
                      <button className="fp-select-btn" onClick={() => handleShowBoundAccounts(fp.id)} title={t('fingerprints.table.accounts')}>
                        <Link size={12} />
                        <span className="fp-select-name">{fp.bound_account_count}</span>
                      </button>
                    </td>
                    <td>
                      <div className="action-buttons">
                        <button className="action-btn" onClick={() => openDetailModal(fp)} title={t('common.detail')}>
                          <CircleAlert size={16} />
                        </button>
                        {!fp.is_original && (
                          <button className="action-btn" onClick={() => openRenameModal(fp)} disabled={actionLoading === `rename-${fp.id}`} title={t('fingerprints.modals.rename.title')}>
                            <Pencil size={16} />
                          </button>
                        )}
                        {!fp.is_original && (
                          <button className="action-btn danger" onClick={() => handleDelete(fp.id)} disabled={actionLoading === fp.id} title={t('common.delete')}>
                            <Trash2 size={16} />
                          </button>
                        )}
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </main>

      {/* Name Input Modal */}
      {showNameModal && (
        <div className="modal-overlay" onClick={closePreviewModal}>
          <div className="modal" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <button className="btn btn-secondary icon-only" onClick={closePreviewModal} title={t('common.back', '返回')} aria-label={t('common.back', '返回')}><ChevronLeft size={14} /></button>
              <h2>{showNameModal === 'generate' ? t('fingerprints.modals.generate.title') : t('fingerprints.modals.capture.title')}</h2>
              <button className="close-btn" onClick={closePreviewModal}><X size={20} /></button>
            </div>
            <div className="modal-body">
              {previewLoading && (
                <div className="empty-state compact">
                  <div className="loading-spinner" style={{ width: 28, height: 28 }} />
                  <div style={{ marginTop: 8 }}>{t('common.loading')}</div>
                </div>
              )}
              <ModalErrorMessage message={previewError} scrollKey={previewErrorScrollKey} />
              {duplicateFingerprint && (
                <div className="action-message warning">
                  {t('fingerprints.messages.duplicate', { name: duplicateFingerprint.name })}
                </div>
              )}
              {previewProfile && (
                <div className="profile-card">
                  <div className="profile-card-header">
                    <span className="profile-card-title">{t('common.preview')}</span>
                  </div>
                  <div className="fp-fields">
                    <div className="fp-field"><span className="fp-label">machineId:</span><span className="fp-value">{previewProfile.machine_id}{isAutoGeneratedField('machineId') ? ` ${t('fingerprints.messages.autoGeneratedSuffix')}` : ''}</span></div>
                    <div className="fp-field"><span className="fp-label">macMachineId:</span><span className="fp-value">{previewProfile.mac_machine_id}{isAutoGeneratedField('macMachineId') ? ` ${t('fingerprints.messages.autoGeneratedSuffix')}` : ''}</span></div>
                    <div className="fp-field"><span className="fp-label">devDeviceId:</span><span className="fp-value">{previewProfile.dev_device_id}{isAutoGeneratedField('devDeviceId') ? ` ${t('fingerprints.messages.autoGeneratedSuffix')}` : ''}</span></div>
                    <div className="fp-field"><span className="fp-label">sqmId:</span><span className="fp-value">{previewProfile.sqm_id}{isAutoGeneratedField('sqmId') ? ` ${t('fingerprints.messages.autoGeneratedSuffix')}` : ''}</span></div>
                    <div className="fp-field"><span className="fp-label">serviceMachineId:</span><span className="fp-value">{previewProfile.service_machine_id || 'NULL'}</span></div>
                  </div>
                </div>
              )}
              <div className="form-group">
                <label>{t('fingerprints.modals.rename.label')}</label>
                <input 
                  type="text" 
                  className="form-input" 
                  placeholder={t('fingerprints.modals.rename.label')} 
                  value={newName}
                  onChange={(e) => {
                    setNewName(e.target.value);
                    if (previewError === t('fingerprints.messages.enterName')) {
                      setPreviewError(null);
                    }
                  }}
                  autoFocus
                />
              </div>
              <div className="modal-actions">
                <button className="btn btn-secondary" onClick={closePreviewModal}>{t('common.cancel')}</button>
                <button 
                  className="btn btn-primary" 
                  onClick={handleCreateFingerprint}
                  disabled={previewLoading || !!actionLoading || !previewProfile || !newName.trim() || !!duplicateFingerprint}
                >
                  {actionLoading ? t('common.saving') : t('common.confirm')}
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Rename Fingerprint Modal */}
      {showRenameModal && (
        <div className="modal-overlay" onClick={() => { setShowRenameModal(null); setRenameName(''); setRenameError(null); }}>
          <div className="modal" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <button className="btn btn-secondary icon-only" onClick={() => { setShowRenameModal(null); setRenameName(''); setRenameError(null); }} title={t('common.back', '返回')} aria-label={t('common.back', '返回')}><ChevronLeft size={14} /></button>
              <h2>{t('fingerprints.modals.rename.title')}</h2>
              <button className="close-btn" onClick={() => { setShowRenameModal(null); setRenameName(''); setRenameError(null); }}><X size={20} /></button>
            </div>
            <div className="modal-body">
              <ModalErrorMessage message={renameError} scrollKey={renameErrorScrollKey} />
              <div className="form-group">
                <label>{t('fingerprints.modals.rename.label')}</label>
                <input 
                  type="text" 
                  className="form-input" 
                  value={renameName}
                  onChange={(e) => {
                    setRenameName(e.target.value);
                    if (renameError) setRenameError(null);
                  }}
                  autoFocus
                />
              </div>
              <div className="modal-actions">
                <button className="btn btn-secondary" onClick={() => { setShowRenameModal(null); setRenameName(''); setRenameError(null); }}>{t('common.cancel')}</button>
                <button 
                  className="btn btn-primary" 
                  onClick={handleRenameFingerprint}
                  disabled={isRenaming}
                >
                  {isRenaming ? t('common.saving') : t('common.confirm')}
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Import Fingerprints Modal */}
      {showImportModal && (
        <div className="modal-overlay" onClick={() => !importing && (setShowImportModal(false), setImportError(null))}>
          <div className="modal" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <button className="btn btn-secondary icon-only" onClick={() => !importing && (setShowImportModal(false), setImportError(null))} title={t('common.back', '返回')} aria-label={t('common.back', '返回')}><ChevronLeft size={14} /></button>
              <h2>{t('fingerprints.modals.import.title')}</h2>
              <button className="close-btn" onClick={() => !importing && (setShowImportModal(false), setImportError(null))}><X size={20} /></button>
            </div>
            <div className="modal-body">
              <ModalErrorMessage message={importError} scrollKey={importErrorScrollKey} />
              <div className="import-options">
                <div className="import-option" onClick={handleImportFingerprintsFromTools}>
                  <div className="option-icon"><FolderOpen size={24} /></div>
                  <div className="option-info">
                    <h4>{t('fingerprints.modals.import.fromTools')}</h4>
                    <p>{t('fingerprints.modals.import.desc')}</p>
                  </div>
                </div>

                <div className="divider">
                  <span>{t('modals.import.orJson')}</span>
                </div>

                <div className="import-json-help">
                  Example: <code>{`[{"name":"Work","profile":{...}}]`}</code>
                </div>

                <textarea
                  className="import-json-input"
                  style={{ width: '100%', height: 100, padding: 8, borderRadius: 6, border: '1px solid var(--border)', background: 'var(--bg-input)', color: 'var(--text-primary)', marginTop: 8 }}
                  value={importJson}
                  onChange={(e) => setImportJson(e.target.value)}
                  disabled={importing}
                />

                <button 
                  className="btn btn-primary full-width" 
                  style={{ marginTop: 12 }} 
                  onClick={handleImportFingerprintsFromJson} 
                  disabled={!importJson.trim() || importing}
                >
                  {importing ? <div className="loading-spinner small" /> : <Download size={16} />}
                  {t('modals.import.importBtn')}
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Bound Accounts Modal */}
      {showBoundAccounts && (
        <div className="modal-overlay" onClick={() => { setShowBoundAccounts(null); setBoundAccountsError(null); }}>
          <div className="modal modal-md" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <button className="btn btn-secondary icon-only" onClick={() => { setShowBoundAccounts(null); setBoundAccountsError(null); }} title={t('common.back', '返回')} aria-label={t('common.back', '返回')}><ChevronLeft size={14} /></button>
              <h2>{t('fingerprints.modals.bound.title')}</h2>
              <button className="close-btn" onClick={() => { setShowBoundAccounts(null); setBoundAccountsError(null); }}><X size={20} /></button>
            </div>
            <div className="modal-body">
              <ModalErrorMessage message={boundAccountsError} scrollKey={boundAccountsErrorScrollKey} />
              <p className="text-muted" style={{ marginBottom: 12, fontSize: 13 }}>
                {t('fingerprints.modals.bound.from', { name: getFpName(showBoundAccounts) })}
              </p>
              
              {!showAddAccounts ? (
                <>
                  <div className="bound-accounts-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 }}>
                    <span>{t('accounts.total', { count: boundAccounts.length })}</span>
                    <button className="btn btn-sm btn-primary" onClick={() => setShowAddAccounts(true)}>
                      <Plus size={14} />{t('fingerprints.modals.bound.add')}
                    </button>
                  </div>
                  {boundAccounts.length === 0 ? (
                    <div className="empty-state" style={{ padding: 20 }}>{t('fingerprints.modals.bound.empty')}</div>
                  ) : (
                    <div className="bound-accounts-list">
                      {boundAccounts.map((acc) => {
                        const tier = getSubscriptionTier(acc.quota);
                        const tierLabel = t(`accounts.tier.${tier.toLowerCase()}`, tier);
                        return (
                          <div key={acc.id} className="bound-account-item">
                            <span className="bound-account-email">{acc.email}</span>
                            <span className="bound-account-tier">{tierLabel}</span>
                          </div>
                        );
                      })}
                    </div>
                  )}
                </>
              ) : (
                <>
                  <div className="bound-accounts-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 }}>
                    <span>{t('fingerprints.modals.bound.select')}</span>
                    <button className="btn btn-sm btn-secondary" onClick={() => { setShowAddAccounts(false); setBoundAccountsError(null); }}>{t('common.cancel')}</button>
                  </div>
                  <div className="bound-accounts-list">
                    {getOtherAccounts().map((acc) => (
                      <label key={acc.id} className={`bound-account-item selectable ${selectedAccountIds.has(acc.id) ? 'selected' : ''}`}>
                        <input 
                          type="checkbox" 
                          checked={selectedAccountIds.has(acc.id)}
                          onChange={() => {
                            const next = new Set(selectedAccountIds);
                            if (next.has(acc.id)) next.delete(acc.id);
                            else next.add(acc.id);
                            setSelectedAccountIds(next);
                          }}
                        />
                        <span className="bound-account-email">{acc.email}</span>
                        <span className="bound-account-from">{t('fingerprints.modals.bound.from', { name: getFpName(acc.fingerprint_id) })}</span>
                      </label>
                    ))}
                    {getOtherAccounts().length === 0 && (
                      <div className="empty-state" style={{ padding: 20 }}>{t('fingerprints.modals.bound.emptyAll')}</div>
                    )}
                  </div>
                  {selectedAccountIds.size > 0 && (
                    <div className="modal-actions">
                      <button 
                        className="btn btn-primary" 
                        onClick={handleAddAccountsToFp}
                        disabled={actionLoading === 'add-accounts'}
                      >
                        {actionLoading === 'add-accounts' ? t('common.saving') : t('fingerprints.modals.bound.add')}
                      </button>
                    </div>
                  )}
                </>
              )}
            </div>
          </div>
        </div>
      )}

      {/* Fingerprint Detail Modal */}
      {showDetailModal && (
        <div className="modal-overlay" onClick={() => setShowDetailModal(null)}>
          <div className="modal" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <button className="btn btn-secondary icon-only" onClick={() => setShowDetailModal(null)} title={t('common.back', '返回')} aria-label={t('common.back', '返回')}><ChevronLeft size={14} /></button>
              <h2>{t('fingerprints.modals.detail.title')}</h2>
              <button className="close-btn" onClick={() => setShowDetailModal(null)}><X size={20} /></button>
            </div>
            <div className="modal-body">
              <div className="profile-card">
                <div className="profile-card-header">
                  <span className="profile-card-title">{showDetailModal.name}</span>
                  {showDetailModal.is_original && <span className="fp-badge fp-badge-pending">{t('fingerprints.messages.readOnly')}</span>}
                </div>
                <div className="fp-fields">
                  <div className="fp-field"><span className="fp-label">machineId:</span><span className="fp-value">{showDetailModal.profile.machine_id}</span></div>
                  <div className="fp-field"><span className="fp-label">macMachineId:</span><span className="fp-value">{showDetailModal.profile.mac_machine_id}</span></div>
                  <div className="fp-field"><span className="fp-label">devDeviceId:</span><span className="fp-value">{showDetailModal.profile.dev_device_id}</span></div>
                  <div className="fp-field"><span className="fp-label">sqmId:</span><span className="fp-value">{showDetailModal.profile.sqm_id}</span></div>
                  <div className="fp-field"><span className="fp-label">serviceMachineId:</span><span className="fp-value">{showDetailModal.profile.service_machine_id || 'NULL'}</span></div>
                  <div className="fp-item-meta" style={{ marginTop: 12 }}>
                    {t('fingerprints.modals.detail.created', { time: new Date(showDetailModal.created_at * 1000).toLocaleString() })}
                  </div>
                </div>
              </div>
              <div className="modal-actions">
                <button className="btn btn-primary" onClick={() => setShowDetailModal(null)}>{t('common.close')}</button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* File Corrupted Modal */}
      {fileCorruptedError && (
        <FileCorruptedModal
          error={fileCorruptedError}
          onClose={() => setFileCorruptedError(null)}
        />
      )}
    </>
  );
}
